// Text folding for Browse's search.
//
// The on-screen keyboard can only produce A-Z, 0-9 and a space. The library
// cannot: it holds Björk, Fennesz's Bécs, Sigur Rós, Motörhead, Ólafur
// Arnalds, Coil's Ø, Zdzisław Łódź. Matching the raw strings means those
// titles are reachable only by a substring that happens to dodge the accented
// letter — and for a title like Ø, by nothing at all.
//
// So both sides of the compare are folded to plain ASCII lower case first.
//
// The table holds BOTH cases of every letter, which is not redundancy.
// Hermes is built without Intl, so its case conversion is ASCII-ONLY: on the
// TV `'Ólafur'.toLowerCase()` returns `'Ólafur'`, not `'ólafur'`. A table keyed
// only in lower case therefore matched under Jest (Node, full Unicode) and
// missed on the device — 46 albums in this library carry an upper-case
// accented letter, Éliane Radigue's seventeen among them. Folding must not
// depend on toLowerCase reaching anything outside ASCII.
//
// This is also a TABLE rather than `String.prototype.normalize('NFD')` plus a
// combining-mark strip, for two reasons. Hermes ships normalize only when
// built with Intl, so relying on it means the behaviour differs between the
// Jest run (Node, always has it) and the TV — the exact split that makes a
// green test suite meaningless. And NFD does not help for the letters that
// are not a base plus a mark: ø, ł, đ, æ, ß and þ decompose to themselves.
// A table covers both cases and behaves identically everywhere.
export const FOLD: Record<string, string> = {
  À: 'a',
  Á: 'a',
  Â: 'a',
  Ã: 'a',
  Ä: 'a',
  Å: 'a',
  à: 'a',
  á: 'a',
  â: 'a',
  ã: 'a',
  ä: 'a',
  å: 'a',
  Ā: 'a',
  ā: 'a',
  Ă: 'a',
  ă: 'a',
  Ą: 'a',
  ą: 'a',
  Æ: 'ae',
  æ: 'ae',
  Ç: 'c',
  ç: 'c',
  Ć: 'c',
  ć: 'c',
  Ĉ: 'c',
  ĉ: 'c',
  Ċ: 'c',
  ċ: 'c',
  Č: 'c',
  č: 'c',
  Ð: 'd',
  ð: 'd',
  Ď: 'd',
  ď: 'd',
  Đ: 'd',
  đ: 'd',
  È: 'e',
  É: 'e',
  Ê: 'e',
  Ë: 'e',
  è: 'e',
  é: 'e',
  ê: 'e',
  ë: 'e',
  Ē: 'e',
  ē: 'e',
  Ĕ: 'e',
  ĕ: 'e',
  Ė: 'e',
  ė: 'e',
  Ę: 'e',
  ę: 'e',
  Ě: 'e',
  ě: 'e',
  Ĝ: 'g',
  ĝ: 'g',
  Ğ: 'g',
  ğ: 'g',
  Ġ: 'g',
  ġ: 'g',
  Ģ: 'g',
  ģ: 'g',
  Ĥ: 'h',
  ĥ: 'h',
  Ħ: 'h',
  ħ: 'h',
  Ì: 'i',
  Í: 'i',
  Î: 'i',
  Ï: 'i',
  ì: 'i',
  í: 'i',
  î: 'i',
  ï: 'i',
  Ĩ: 'i',
  ĩ: 'i',
  Ī: 'i',
  ī: 'i',
  Ĭ: 'i',
  ĭ: 'i',
  Į: 'i',
  į: 'i',
  İ: 'i',
  ı: 'i',
  Ĵ: 'j',
  ĵ: 'j',
  Ķ: 'k',
  ķ: 'k',
  Ĺ: 'l',
  ĺ: 'l',
  Ļ: 'l',
  ļ: 'l',
  Ľ: 'l',
  ľ: 'l',
  Ł: 'l',
  ł: 'l',
  Ñ: 'n',
  ñ: 'n',
  Ń: 'n',
  ń: 'n',
  Ņ: 'n',
  ņ: 'n',
  Ň: 'n',
  ň: 'n',
  Ò: 'o',
  Ó: 'o',
  Ô: 'o',
  Õ: 'o',
  Ö: 'o',
  Ø: 'o',
  ò: 'o',
  ó: 'o',
  ô: 'o',
  õ: 'o',
  ö: 'o',
  ø: 'o',
  Ō: 'o',
  ō: 'o',
  Ŏ: 'o',
  ŏ: 'o',
  Ő: 'o',
  ő: 'o',
  Œ: 'oe',
  œ: 'oe',
  Ŕ: 'r',
  ŕ: 'r',
  Ŗ: 'r',
  ŗ: 'r',
  Ř: 'r',
  ř: 'r',
  Ś: 's',
  ś: 's',
  Ŝ: 's',
  ŝ: 's',
  Ş: 's',
  ş: 's',
  Š: 's',
  š: 's',
  Ș: 's',
  ș: 's',
  ß: 'ss',
  ẞ: 'ss',
  Ţ: 't',
  ţ: 't',
  Ť: 't',
  ť: 't',
  Ŧ: 't',
  ŧ: 't',
  Ț: 't',
  ț: 't',
  Þ: 'th',
  þ: 'th',
  Ù: 'u',
  Ú: 'u',
  Û: 'u',
  Ü: 'u',
  ù: 'u',
  ú: 'u',
  û: 'u',
  ü: 'u',
  Ũ: 'u',
  ũ: 'u',
  Ū: 'u',
  ū: 'u',
  Ŭ: 'u',
  ŭ: 'u',
  Ů: 'u',
  ů: 'u',
  Ű: 'u',
  ű: 'u',
  Ų: 'u',
  ų: 'u',
  Ŵ: 'w',
  ŵ: 'w',
  Ý: 'y',
  ý: 'y',
  ÿ: 'y',
  Ŷ: 'y',
  ŷ: 'y',
  Ÿ: 'y',
  Ź: 'z',
  ź: 'z',
  Ż: 'z',
  ż: 'z',
  Ž: 'z',
  ž: 'z',
};

// toLowerCase handles A-Z, which it does correctly everywhere; the table
// handles the rest in whichever case it arrives. Characters with no entry pass
// through untouched, so punctuation, digits and CJK are left exactly as they
// are — this narrows the alphabet, it does not strip the string.
//
// Note a folded character can widen the string (ß -> ss), which is why this
// builds a new string rather than mapping in place.
export function fold(s: string): string {
  const lower = s.toLowerCase();
  let out = '';
  for (const ch of lower) {
    out += FOLD[ch] !== undefined ? FOLD[ch] : ch;
  }
  return out;
}
